### ISSUE TITLE
New feature: Enable pausing a product executor for maintenance

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1305]
## Current situation
When doing a backend update (PDS-Solution, Checkmarx, ...) then the backend is unreachable for a short amount of time.

As a workaround, we currently stop the job scheduling on the server and wait until the job queue is empty.
During this time all incoming jobs get queued. After starting job scheduling again, it can take much time until the queue is processed.

Imagine, we have 10 backends attached, then while working on one, the other nine are idle, but could process scans.

## Wanted
A possibility to "pause" an executor.
- no new jobs will be run using this executor
- wait until the currently active jobs of this executor are done

After ending the "pause"
- the jobs waiting for this executor are continued

**Comment by de-jcup** [comment]
Interesting idea.

But the proposal of "pausing" an executor would also have following impacts.

- we would need an overview over all paused executors
- we would need start,stop,status per product executor (configuration)
- every product executor would need to periodically check if it (respectively its configuration) paused or not.
  Talking about configurations -  this problematic because every product executor config for product X may not work because 
  product X is updated (when directly connected via adaper). When we are talking about PDS, we can talk about configuration level.
- PDS solutions : scripts already started would be still running while "paused" - because pausing the scripts would be too much effort

At PDS side we could do following:

- rest call to PDS and set as "paused". stores in database. so pause/unpause + status rest operations necessary
- a paused PDS would still execute its running job
- a paused PDS would deny new job queuing and no longer starts new jobs. The job queue deny would result in a dedicated "paused" error result so PDS product executor would know that the product delegation server is just paused. In this case the PDS product exeuctors should have a resilience consultant implementation which just would do n retries with pauses of x minutes. 
- in combination with current queue status (already available) it is possible to automate a deployment (pause + wait until jobs done than start new deployment + after it + unpause...)
- when #1415  has been done and also #1416 only nessus and netsparker implementations are not PDS variants. And those will be either deprecated or also migrated in future. So using PDS here again gives us multiple possiblitilies.
