### ISSUE TITLE
Get both HTML and JSON report at the same time

### ISSUE THREAD

**Issue by dAnjou** [mercedes-benz/sechub#1346]
Hi,

is it possible to get both reports at the same time with the command line client?

Our use case is that we'd like to have the detailed HTML report for humans and the JSON report for further processing in our observability stack.

Thanks!

**Comment by Jeeppler** [comment]
The moment you scan your project using SecHub, you will receive a SecHub JobUUID. The SecHub JobUUID is unique to the scan. You can always use it get the report in either HTML or JSON. The only thing you need to is the SecHub JobUUID of the job. You can save the SecHub JobUUID in a variable or file.

Let's assume your SecHub JobUUID is: `1b9fe5ae-e1bd-11ec-a0ae-7b003d0318b3`. Then you can get the HTML and JSON report like so:

~~~
sechub -jobUUID 1b9fe5ae-e1bd-11ec-a0ae-7b003d0318b3 -reportformat json getReport
sechub -jobUUID 1b9fe5ae-e1bd-11ec-a0ae-7b003d0318b3 -reportformat html getReport
~~~

Because `json` is the default format, the explicit `-reportFormat json` can be omitted:

~~~
sechub -jobUUID 1b9fe5ae-e1bd-11ec-a0ae-7b003d0318b3 getReport
~~~

It is possible to get the job report at any given point in time from the server. However, the SecHub administrator might have set a retention policy for the reports.

For more information have a look at the client documentation:

- https://mercedes-benz.github.io/sechub/latest/sechub-client.html#getreport
- https://mercedes-benz.github.io/sechub/latest/sechub-client.html#commandline-options

@sven-dmlr I think we should add an example to the documentation on how to use the combination `getReport`, `-jobUUID` and `-reportFormat` to get the report in different formats.

**Comment by sven-dmlr** [comment]
@Jeeppler I've just created #1369

**Comment by dAnjou** [comment]
Thanks for addressing this!

I'd be curious what a good way would be to get the `jobUUID`. Currently I'm doing this in our CI pipeline:
```
sechub -output ./sechub-report scan
for report in ./sechub-report/*.json; do
  sechub -jobUUID "$(jq -r '.jobUUID' "$report")" -reportformat html -output ./sechub-report getReport
done
```
This doesn't look too nice and it has another flaw, will get into that in the end.

The scan will put a JSON report in `./sechub-report` (which doesn't exist at that point) but the filename will contain the job UUID which I don't know beforehand. So, I have to do the globbing and I'm doing the `for` just in case even though there's probably only ever one single JSON report in the directory. Then I get the job UUID from inside the JSON report to get the HTML report.

Is there maybe a better way to get the job UUID?

The other flaw with that approach is when the scan has a non-zero exit code. Then our script aborts (`set -e`) and it won't fetch the HTML report.

While I can script my way around that somehow, it'd be quite a bit more convenient to get both reports with a single scan command. Maybe you could accept a comma-separated list of formats, i.e. `-reportformat html,json`?

**Comment by sven-dmlr** [comment]
Hi @dAnjou 
when you call the client, then the jobUUID is printed several times.

So you could script it like this:
```bash
# Run scan and get report as JSON plus read jobUUID:
JOBUUID=`sechub scan | grep "Fetching result" | awk '{print $9}'`
# Get HTML Report
sechub-0.31.0 -jobUUID $JOBUUID -reportformat html getReport
```

**Comment by dAnjou** [comment]
This is not really a good option in my opinion, because in my experience log output like this is considered to be for humans and therefore developers tend to change it without thinking about the implications (no offence, I've done that myself).

So while today the line looks like this:
```
2022-06-06 18:09:13 (Z) Fetching result (format=html) for job 2ab1123e-4f15-4e76-a191-9923dd40a52c
```
Tomorrow it might look like this for whatever reason:
```
2022-06-06 18:09:13 (Z) Fetching result (format: html) for job UUID 2ab1123e-4f15-4e76-a191-9923dd40a52c
```
So I'd rather not rely on parsing output intended for humans.

---

Which still leaves the other bigger pain point:

> The other flaw with that approach is when the scan has a non-zero exit code. Then our script aborts (`set -e`) and it won't fetch the HTML report.

Please reconsider the multiple formats feature (`-reportformat html,json`), it seems pretty backwards-compatible and straight-forward to implement.

---

Btw., what I've also tried is `-output ./sechub-report/report.json` so I can avoid the globbing. According to the docs it accepts a file path:

> `-output <path to folder or file>`
> Where to place reports, false-positive files etc. Can be a directory, a file name or a file path (defaults to current working directory and default file names)

But somehow it creates a file like this: `sechub-report/report.json/sechub_report_xyz_2ab1123e-4f15-4e76-a191-9923dd40a52c.json`.

Probably a separate issue though.

**Comment by sven-dmlr** [comment]
You can safely upgrade the client.

We are extending the server api, but always are backwards compatible (existing api calls/json configs will still work).
