### ISSUE TITLE
PDS-owaspzap sometimes fails because node runs low on ephemeral-storage

### ISSUE THREAD

**Issue by winzj** [mercedes-benz/sechub#1505]
### Situation
After some scans or long running scans sometimes the scan fails because the node runs low on ephemeral storage. This issue might be caused by big log files, log files that are not removed or maybe both. This needs to be investigated.

### Wanted
Enough ephemeral-storage, so the container can keep running.

**Comment by Jeeppler** [comment]
By default the container uses the local node storage in K8s.

[Ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) is a temporary storage, but from an external storage pool. The ephemeral volume will be created during the container initialization and is removed the moment the container stops (shutdown/reschedule). Ephemeral volumes are fairly new feature introduced with K8s 1.23 (version as of writing is v1.24.3). 

One would have to add the option to use ephemeral volumes to the Helm Chart of OWASP ZAP. PDS Scancode uses ephemeral volumes already, have a look at PDS Scancode for inspiration.

Because the ephemeral volumes feature is new, the user should be able to enable and disable the ephemeral volume option through the values.yaml file. By default, ephemeral storage should be disabled.
