### ISSUE TITLE
database table adm_job_information may cause sql exceptions

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1562]
## Situation
When stopping a sechub server without prior stopping the scheduler, it happened that afterwards in table `sechub.adm_job_information` there were two entries of the same `job_uuid`.
This led to an sql exception because it is expected that for one job_uuid there should be only one row returned.

The only fix was to remove the duplicate rows directly in the database.

```
                      Table "sechub.adm_job_information"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 uuid          | uuid                        |           | not null |
 job_uuid      | uuid                        |           | not null |
 project_id    | character varying(60)       |           | not null |
 owner         | character varying(60)       |           | not null |
 status        | character varying(30)       |           | not null |
 since         | timestamp without time zone |           | not null |
 info          | character varying(512)      |           |          |
 configuration | character varying(8912)     |           |          |
 version       | integer                     |           |          |
Indexes:
    "adm_job_information_pkey" PRIMARY KEY, btree (uuid)
```

## Wanted
Avoid these exceptions.

Idea:
- either: create an unique constraint on column `job_uuid`
- or: make `job_uuid` the primary key instead of creating a separate `uuid` column

**Comment by de-jcup** [comment]
@sven-dmlr : Please do me a favor and add next time the exception stacktrace to the issue. It is hard to find the query without the information

**Comment by de-jcup** [comment]
## Decisions
### PK change
We decided to remove `uuid` and to use `jobuuid` as PK instead.

### Data migration
The flyway db scripts will drop the old job information table and create a new one.
This  will remove all existing job information in adminstration.

But because the job information entity  is automatically deleted when a job is done and we must already wait for all jobs to be done before we do the update (with disabled scheduling),  we simply delete the existing job information table.
