### ISSUE TITLE
Provide Helm Chart for SecHub

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1567]
Provide a Helm Chart for SecHub. The helm chart will allow one to run SecHub in a Kubernetes cluster.

Part of: #320

**Comment by ddzikon** [comment]
I would like to install the SecHub Server Helm chart to a local K8s cluster (`minikube`), but I've stumbled upon a few issues:

1. `ghcr.io/mercedes-benz/sechub/server` Docker image does not seem to exist (I tried with `docker pull`). Should it be publicly available or is the expectation to build it locally?

2. I tried building the image and storing it in private registry, but after doing `helm install`, SecHub pod crashed due to missing environment variables (required by the `run.sh` script):
    * `SECHUB_MAX_FILE_UPLOAD_SIZE` - a new counterpart for it is probably `SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE` and `SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE`
    * `ADMIN_USERID`
    * `ADMIN_APITOKEN`
    * `SECHUB_START_MODE` 

3. I added these environment variables to Chart's `values.yaml`, but the SecHub server still does not seem to be starting properly (startup probe fails: `Startup probe failed: Get "https://172.17.0.6:8443/api/anonymous/check/alive": dial tcp 172.17.0.6:8443: connect: connection refused`)


Do you happen to know what is going on? Am I missing some important steps or is it the Helm chart?

**Comment by sven-dmlr** [comment]
Hello @ddzikon 
this change was the first step to be able to deploy the SecHub server on k8s.
You are right: It currently does not yet work.

I will create follow-up issues to get this work...
---
Your questions:
1. right: the Docker image is supposed to be on ghcr.io. There is no upload yet.
2. the run.sh needs an update. (At our internal installation we currently have a different `run.sh`. Here the Helm chart works)
3. the run.sh needs an update.
