### ISSUE TITLE
Rename uri to url inside the sechub webscan json config

### ISSUE THREAD

**Issue by winzj** [mercedes-benz/sechub#1793]
### Situation
Currently the the sechub webscan json config looks like this:
```json
{
    "apiVersion": "1.0",
    "webScan": {
        "uri": "https://productfailure.demo.example.org",
        "login": {
            "url": "https://productfailure.demo.example.org/login",
           .....
        }
    }
}
```
The target to scan is entered into a field called `uri` but the for the login the field is called `url`.
This can lead to confusion for users.

## Wanted
It should be as easy as possible for users to understand the configuration and make as few mistakes as possible.

### Idea
We could use a Jackson annotation to enable both names for both fields, like `@JsonAlias({"url"})` and `@JsonAlias({"uri"})` or  `@JsonAlias({"uri", "url"})`

**Comment by Jeeppler** [comment]
I would prefer to only use the term Uniform Resource Locator (URL). URLs are a subset of URIs (Uniform Resource Identifier). URIs can address anything. URLs are used to identify resources on a network:

> A URI can be further classified as a locator, a name, or both.  The
   term "Uniform Resource Locator" (URL) refers to the subset of URIs
   that, in addition to identifying a resource, provide a means of
   locating the resource by describing its primary access mechanism
   (e.g., its network "location"). "

> source: https://datatracker.ietf.org/doc/html/rfc3986#section-1.1.3

Because, the context is a webScan we can safely assume, that we want to only scan resources located in a network, therefore the only term which would make sense would be a URL. At least in my eyes.

While aliasing attributes is possible with Jackson, I would keep it simple and limit it to only one term: `url`.

**Comment by winzj** [comment]
That is what I thought as well, `ùrl` makes more sense. The only downside if we change this is, existing configurations need to be changed.
