### ISSUE TITLE
SecHub API: Get jobs with labels

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#2058]
# Feature

With #2040 the user can provide labels, additional meta data, which are available as meta data in the report as well. Be able to query for jobs with specific labels attached to them (see: [UC_071-User lists jobs for project](https://mercedes-benz.github.io/sechub/latest/sechub-architecture.html#section-usecase-UC_071)).

**Comment by de-jcup** [comment]
## Example
Here a snapshot for the current label definition which can be done inside a SecHub configuration file (`sechub.json`)
```
"metaData": {
     "labels": {
        "stage": "testing", 
        "purpose": "quality assurance" 
    }
  }
```
## Points to discuss

### Data storage
Currently the label information is not stored inside database in own columns- means the label information is only available inside the combined report information (JSON).

To handle this fast and correctly we would need to introduce a new data table inside scan domain which contains the data. It should just reference the `ScanReport` uuid 

###  Query syntax
The mentioned use case is a `GET` call - means: We provide all parameter inside the URL. It would be possible to provide a body here as well, but this would be .... very odd.

#### Syntax proposal 1:
```
/api/project/{project}/Jobs (as before)
/api/project/{project}/Jobs?metadata.labels.stage=testing&metadata.labels.purpose=quality%20assurance
```
#### Syntax proposal 2:
```
/api/project/{project}/Jobs (as before)
/api/project/{project}/Jobs/metadata/labels/stage=testing&purpose=quality%20assurance
```
#### Syntax proposal 3:
```
/api/project/{project}/Jobs (as before)
TBD
```
### Existing reports /Data migration
The labels were introduced with #2040 - in the meantime users can have used the feature, but the data cannot be used directly in SQL queries.

Data migration is not part of this issue. When the issue is done the tables are wellknown and a Database collector script could be written which could fetch jobs, inspect data and create artifical/follow up entries. But this only optional and a operational task. 

### Client feature
The go client would need to be extended as well (another issue)
