### ISSUE TITLE
Bug docker-compose.sh starts wrong server version

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#2953]
# Problem

Executing this will cause issues:

~~~
$ ./sechub-api.sh user_signup "pauli" "user@example.org"
HTTP/1.1 400 
{"status":400,"error":"Bad Request","message":"Validation failed for object='signupJsonInput'. Error count: 1","details":["Field 'emailAdress' with value 'null' was rejected. Invalid email adress"],"timeStamp":"Sat Mar 02 22:11:32 UTC 2024"}
~~~

Changing the bash function for generating 

~~~
function generate_sechub_user_signup_data {
  cat <<EOF
{
  "apiVersion":"$SECHUB_API_VERSION",
  "userId":"$1",
  "emailAdress":"$2"
}
EOF
}
~~~

Results in:

~~~
$ ./sechub-api.sh user_signup "pauli" "user@example.org"
HTTP/1.1 200
~~~

# Solution

With #2874 the email address was renamed properly to `address` with two `d`s across the entire code base. The current code:

~~~
function generate_sechub_user_signup_data {
  cat <<EOF
{
  "apiVersion":"$SECHUB_API_VERSION",
  "userId":"$1",
  "emailAddress":"$2"
}
EOF
}
~~~

should work. Otherwise what was the point of renaming it.

# Impact 

The getting started guide does not work: https://mercedes-benz.github.io/sechub/latest/sechub-getting-started.html

**Comment by Jeeppler** [comment]
@de-jcup and @sven-dmlr please have a look.

**Comment by sven-dmlr** [comment]
The sechub-api.sh file must match the running server version.
But in `sechub-solution/env` is downloading of version "1.3.0" configured.
In order to be safe, the default build type should be changed to "build".

**Comment by Jeeppler** [comment]
@sven-dmlr from my perspective changing the build type to "build" is not the best solution. It will take a lot more time to start the solution, because it needs to build everything. In addition, the build is done from the development branch, which makes issues beginners have much harder to replicate.

**Comment by sven-dmlr** [comment]
Yes: the first time it takes more time. All subsequent calls are as quick as before.
IMHO the build from the `develop` branch makes sense, because it's the default branch from where the `sechub-api.sh` script also stems.
For beginners this should be okay.
(It's a big effort to change the `env` file with _every_ server release: extra issue+extra PR )

We discussed in the team that for the future we could use a local Kubernetes like Minikube for a quick start. So the existing container packages and Helm charts can be used.

Although for developing, Docker Compose could still make sense.
