### ISSUE TITLE
[WebUI] Use Case: Overview of project Jobs

### ISSUE THREAD

**Issue by lorriborri** [mercedes-benz/sechub#3451]
## Situation
No Overview if projects jobs

## Wanted
When clicking on a project I want to view the jobs that have been started for the project. There should be an state, to see if the job is already finished or still running or was canceled. Also I wish to see the color of the traffic light.

## Solution
- Jobs listed with pagination
- Refresh Button for view
- Job status
- Job result
- Job stage

![Projekt Auswahl - Scan Status](https://user-images.githubusercontent.com/122868367/214894818-ad9be5cc-32db-4e9f-bef4-dd123af77340.png)

**Comment by haerter-tss** [comment]
My suggestion would be to deliver a similar output as the Sechub client does when listing jobs. Here it currently looks like this:

`sechub -project my_project_name listjobs`

![image](https://github.com/user-attachments/assets/06a854bb-f671-40cf-8a01-afcdb7315430)

Since the Web UI will show jobs for all projects that my user is assigned to instead of just a project that I define I think it would be useful if there would be another row that is called "Project" that shows from which project the jobs originate.
