### ISSUE TITLE
Proposal: PDS + Scan

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#370]
[Scan](https://github.com/ShiftLeftSecurity/sast-scan) is a tool which combines several FOSS SAST + SCA scanners into one tool. For several FOSS SAST tools, Scan is able to convert the output into SARIF and therefore returns the report in the SARIF format.

It would be beneficial to integrate Scan with the Product Delegation Server (PDS). The combination of PDS + Scan would allow us to test both PDS and SecHub. In addition, it is possible to make sure that SecHub can work with SARIF reports.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
Related to: #364

**Comment by Jeeppler** [comment]
Scan supports Bandit and GoSec as scanners to scan Python and Go: https://slscan.io/en/latest/

See: #361, #362

**Comment by PTheocharis** [comment]
Hello, Im a beginner in coding and I see you have labeled this as a good first issue, however it was added in 2021 and the issue is from 2020. Is it still ongoing? This is a project from my class and I want to improve my knowledge around code vulnerability. Thanks in advance!

**Comment by Jeeppler** [comment]
@de-jcup and @sven-dmlr please have a look.

**Comment by sven-dmlr** [comment]
@PTheocharis We are checking if this issue is still needed. We'll give notice soon.

Btw: Creating a PDS-solution is no simple task. If you are a beginner in coding, you could have a look at the other "good first issue" tasks. We are regularly working on increasing this list.

**Comment by lorriborri** [comment]
Hi @PTheocharis 
We have checked the issue and unfortunately discovered that it is outdated.
The Scan GitHub repository is currently not maintained, and there is no documentation available since the new documentation is not yet online, but the old one (slscan.io) is already offline.
Additionally, we have already integrated some of the tools into SecHub, which Scan also uses.

**Comment by lorriborri** [comment]
Hi @PTheocharis 
We have checked the issue and unfortunately discovered that it is outdated.
The Scan GitHub repository is currently not maintained, and there is no documentation available since the new documentation is not yet online, but the old one (slscan.io) is already offline.
Additionally, we have already integrated some of the tools into SecHub, which Scan also uses.
