### ISSUE TITLE
Client: Implement traffic light `OFF`

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#810]
SecHub client must be able to handle the `OFF` value introduced with #809 .

- At this point #806 must be already done.
- In case of `OFF` (or a missing traffic light) we must always break because there is no longer a way to decide if the build is broken or not. The user shall be informed to inspect the messages from serve side printed by the client.

**Comment by de-jcup** [comment]
sub issue for #808

**Comment by sven-dmlr** [comment]
Looked into it:
Currently all displayed status information comes from the `get status` call (https://mercedes-benz.github.io/sechub/latest/sechub-restapi.html#user-checks-sechub-job-state) - not from the report.
This makes sense, because if the report format is html, the above mentioned informations are not present (additionally, parsing a html file is not easy).

So the `get status` call should contain all informations about failures.
(and a scan summary (w critical findings, x high, y medium, z low) if we want the SecHub client to display this information)

Currently, the status call contains these informations:
```json
{
  "jobUUID": "37008e19-f592-4afb-b11d-d45faad23725",
  "owner": "myuser",
  "created": "2022-02-03T16:32:50.631346",
  "started": "2022-02-03T16:32:51.885962",
  "ended": "2022-02-03T16:32:52.044051",
  "state": "ENDED",
  "result": "OK",
  "trafficLight": "RED"
}
```

**Comment by Jeeppler** [comment]
To make it report format agnostic, we agreed to add the `messages` to the `get status` call.

~~~json
{
  "jobUUID": "37008e19-f592-4afb-b11d-d45faad23725",
  "owner": "myuser",
  "created": "2022-02-03T16:32:50.631346",
  "started": "2022-02-03T16:32:51.885962",
  "ended": "2022-02-03T16:32:52.044051",
  "state": "ENDED",
  "messages" :  [ 
                  {
                       "type" : "ERROR",
                       "text" : "The code scan execution did fail"
                  }
  ]
  "result": "OK",
  "trafficLight": "RED"
}
~~~
